name: scentview
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # ✅ Firebase
  firebase_core: ^3.1.1      
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.3
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.0.0
  local_auth: ^2.1.7

  # ✅ UI & Utils
  iconsax: ^0.0.8            
  provider: ^6.1.1
  image_picker: ^1.0.7       
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  font_awesome_flutter: ^10.7.0
  path_provider: ^2.1.2
  
  # ✅ Media & Network
  video_player: ^2.9.1
  flutter_svg: ^2.0.10
  http: ^1.2.2
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.3.1
  slide_countdown: ^2.0.2    
  mime: ^1.0.5
  http_parser: ^4.0.0
  
  # ✅ Offline Mode
  sqflite: ^2.3.0
  path: ^1.9.0
  connectivity_plus: ^6.0.3

  # ✅ Lints & Extra
  flutter_lints: ^4.0.0
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/homepage images/
    - assets/logo-name/
    - assets/video/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo-name/logo1.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/logo-name/logo1.png
  min_sdk_android: 21
  web:
    generate: false

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/logo-name/logo1.png
  image_dark: assets/logo-name/logo1.png
  android_12:
    color: "#FFFFFF"
    color_dark: "#000000"
    image: assets/logo-name/logo1.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#000000"
  android: true
  ios: true
  web: true